export const ROUTES = {
    HOME: "/",
    SHOP: "/shop",
    PRODUCT_DETAILS: "/product/:id",
    CART: "/cart",
    CHECKOUT: "/checkout",
    ORDER_SUCCESS: "/order-success",
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    FORGOT_PASSWORD: "/auth/forgot-password",
    DASHBOARD: "/user/dashboard",
    PROFILE: "/user/profile",
    ORDERS: "/user/orders",
    WISHLIST: "/user/wishlist",
    SETTINGS: "/user/settings",
    CATEGORY: "/category/:slug",
    SEARCH: "/search",
    ABOUT: "/about",
    CONTACT: "/contact",
    FAQ: "/faq",
    TERMS: "/terms",
    PRIVACY: "/privacy",
    NOT_FOUND: "*",
};
